### ISSUE TITLE
Licensing issue with libreadline

### ISSUE THREAD

**Issue by astillich** [cvjena/cn24#52]
Readline is licensed under the [GNU GPL](https://en.wikipedia.org/wiki/GNU_Readline#Choice_of_the_GPL_as_GNU_Readline.27s_license), linking against it makes the whole library fall under this license. I see two possible solutions here:

1) Add a CMake flag to disable the shell and skip linking to readline. This is what I'll do for our copy of the lib. I'm using CN24 as a library, so that's OK for me.
2) Integrate a readline alternative. There's [editline](http://thrysoee.dk/editline/) and [linenoise](https://github.com/antirez/linenoise)

**Comment by cabrust** [comment]
Hi,
thank you for bringing this to our attention. We will switch to another readline-like library because the GPL terms are too restrictive and we do not wish to impose too many restrictions for our users. I was under the impression that readline is LGPL software, but it is not. Linenoise seems like a reasonable choice.
~Clemens
